#!/usr/bin/env bash
# check if configuration is correct

query_dns() {
    local subdomain="$1"
    local domain="$2"
    local record_type="$3"
    local destination="$4"

    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Main script
main() {
    local domain="$1"
    local subdomain="$2"

    # Default subdomains to query
    subdomains=("www" "lb-01" "web-01" "web-02")

    # If a subdomain is provided as an argument, query only that subdomain
    if [ -n "$subdomain" ]; then
        subdomains=("$subdomain")
    fi

    for subdomain in "${subdomains[@]}"; do
        result=$(dig "$subdomain.$domain" +short)

        if [ -n "$result" ]; then
            record_type=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | awk '/IN/ {print $4}')
            query_dns "$subdomain" "$domain" "$record_type" "$result"
        fi
    done
}

# Check for the correct number of arguments
if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

# Call the main function with provided arguments
main "$@"