#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

# Update packages and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Create a simple HTML page with "Hello World"
echo "Hello World" | sudo tee /var/www/html/index.html

# Configure Nginx to perform the redirection
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.facebook.com/ permanent;' /etc/nginx/sites-available/default

# Restart Nginx to apply the configuration changes
sudo service nginx restart
