#!/usr/bin/env bash
# mysql backup dump
CURRENT_DATE=$(date +"%d-%m-%Y")
sudo mysqldump --all-databases --user=root --password=$1 > backup.sql
tar -czvf "$CURRENT_DATE.tar.gz" backup.sql
rm backup.sql
