#!/usr/bin/env bash
# long func that prints and prevents killing it

function ex() {
	rm /var/run/myscript.pid
	exit
}

trap "echo I hate the kill command;ex" SIGTERM
trap "echo Y U no love me?!;ex" SIGINT

echo $$ >> /var/run/myscript.pid
while [ true ]; do
	echo To infinity and beyond;
done
