#!/usr/bin/env bash
# long func that prints and prevents killing it

pid_file="/var/run/myscript.pid"

# removes then exits func
function ex()
{
	rm -f "$pid_file"
	exit 0
}

#hundle sigterm
trap "echo I hate the kill command;ex" SIGTERM

#hundle sigint
trap "echo Y U no love me?!;ex" SIGINT

#hundles sigquit
trap "exit" SIGQUIT

echo $$ > "$pid_file"

#print till infinity
while [ true ]; do
	echo To infinity and beyond;
done
