#!/usr/bin/env bash
# long func that prints and prevents killing it

# removes then exits func
function ex() {
	rm /var/run/myscript.pid
	exit
}

#hundle sigterm
trap "echo I hate the kill command;ex" SIGTERM

#hundle sigint
trap "echo Y U no love me?!;ex" SIGINT

echo $$ >> /var/run/myscript.pid

#print till infinity
while [ true ]; do
	echo To infinity and beyond;
done
