#!/usr/bin/env bash
# does something i cant explain

start_process() {
	./manage_my_process &
	echo $! > /var/run/my_process.pid
	echo "manage_my_process started"
}

#function to stop proc
stop_process() {
	if [ -f "/var/run/my_process.pid" ]; then
		pid=$(cat /var/run/my_process.pid)
		kill $pid
		rm -f /var/run/my_process.pid
		echo "manage_my_process stopped"
	else
		echo "manage_my_process stopped"
	fi
}

# Check for argument and execute the corresponding function
case "$1" in
	"start")
		start_process
		;;
	"stop")
		stop_process
		;;
	"restart")
		restart_process
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
