#!/usr/bin/env bash
# does something i cant explain

start_process() {
	./manage_my_process &
	echo $$ > /var/run/my_process.pid
	echo "manage_my_process started"
}

#function to stop proc
stop_process() {
	[ -e "/var/run/my_process.pid" ] && pkill -f "./manage_my_process" && rm /var/run/my_process.pid
	echo "manage_my_process stopped"
}

#restart process
restart_process() {
	"$0" stop >& /dev/null
	"$0" start >& /dev/null
	echo "manage_my_process restarted"
}

# Check for argument and execute the corresponding function
case "$1" in
	"start")
		start_process
		;;
	"stop")
		stop_process
		;;
	"restart")
		restart_process
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
