#!/usr/bin/env bash
# script that resolves 127.0.0.1 -> 127.0.0.2 and 
# facebook.com -> 8.8.8.8

cp /etc/hosts ~/temp
sed -i a/127.0.0.1/127.0.0.2/ ~/temp
echo "8.8.8.8 facebook.com" >> ~/temp
cp -f ~/temp /etc/hosts
